INSERT INTO brand_model ( BRAND_MODEL ) VALUES ('NC 700');
INSERT INTO brand_model ( BRAND_MODEL ) VALUES ('Goldwing 1200');
INSERT INTO brand_model ( BRAND_MODEL ) VALUES ('Ninja 750');
INSERT INTO brand_model ( BRAND_MODEL ) VALUES ('Iron 883');
INSERT INTO motor_cycle ( brand, chassis_number, motor_number, BRAND_MODEL_ID ) VALUES ('Honda', '20131234', '43213102', 1);
INSERT INTO motor_cycle ( brand, chassis_number, motor_number, BRAND_MODEL_ID ) VALUES ('Harley Davidson', '20202345', '54320202', 4);
INSERT INTO motor_cycle ( brand, chassis_number, motor_number, BRAND_MODEL_ID ) VALUES ('Honda', '20183678', '87638102', 2);
INSERT INTO motor_cycle ( brand, chassis_number, motor_number, BRAND_MODEL_ID ) VALUES ('Kawasaki', '20075214', '41257002', 3);
INSERT INTO motor_cycle ( brand, chassis_number, motor_number, BRAND_MODEL_ID ) VALUES ('Honda', '20135577', '77553102', 1);
INSERT INTO owner ( OWNER_NAME ) VALUES ('Morten Eiby');
INSERT INTO owner ( OWNER_NAME ) VALUES ('Hans Hansen');
INSERT INTO owner ( OWNER_NAME ) VALUES ('Karina Enna');
INSERT INTO owner ( OWNER_NAME ) VALUES ('Bob Jensen');
INSERT INTO owner_motorcycles (OWNERS_ID, MOTORCYCLES_ID ) VALUES (1, 1);
INSERT INTO owner_motorcycles (OWNERS_ID, MOTORCYCLES_ID ) VALUES (3, 1);
INSERT INTO owner_motorcycles (OWNERS_ID, MOTORCYCLES_ID ) VALUES (1, 2);
INSERT INTO owner_motorcycles (OWNERS_ID, MOTORCYCLES_ID ) VALUES (2, 3);
INSERT INTO owner_motorcycles (OWNERS_ID, MOTORCYCLES_ID ) VALUES (4, 4);
INSERT INTO owner_motorcycles (OWNERS_ID, MOTORCYCLES_ID ) VALUES (3, 5);